### ISSUE TITLE
请问docker可以实现这样的功能吗,还是django效果更好?

### ISSUE THREAD

**Issue by Bruce337f** [wolverinn/stable-diffusion-multi-user#8]
在哪里能够获取更详细的api教程,因为在示例中并没有提到其他能用的扩展,例如脚本的使用?

**Comment by wolverinn** [comment]
更新了一版大的，更新到了torch2.0，支持了插件的API调用，API和webui的API保持一致

**Comment by wolverinn** [comment]
也有docker的方案，在option2和3里面
